version: "3.9"

services:
  fin_api_database:
    image: postgres
    container_name: fin_api_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fin_api
      - POSTGRES_PASSWORD=fin_api123
      - POSTGRES_DB=fin_api_database
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - fin_api_database
    depends_on:
      - fin_api_database

volumes:
  pgdata:
